using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SUVAN.BackOffice.Models.ViewModel.Enums
{
  /// <summary>
  /// Enumerador de opciones de menu para el sistema
  /// </summary>
  public enum EnumOpcionMenu : int
  {
    seguridad = 1,
    usuarios = 2,
    perfiles = 3,
    permisos = 4,
    configuracion = 5,
    comercial = 6,
    monitoreo = 7,
    ingresos = 8,
    capacitacion = 9,
    analitica = 10,
    pagoaoperador = 11,
    contenidos = 12,
    empresas = 13,
    conductores = 14,
    unidades = 15,
    tarifas = 16,
    descuentos = 17,
    promociones = 18,
    estaciones = 19,
    tramos = 20,
    rutas = 21,
    corridas = 22,
    envioDecorreos = 23,
    gestionDeNotificaciones = 24,
    temas = 25,
    divisas = 26,
    viajes = 27,
    gestionDeMonederos = 28,
    codigosDePromocion = 29,
    apisExternas = 30,
    pasarelaDePago = 31,
    despachoDeViaje = 32,
    ubicacionDeUnidadEnTiempoReal = 33,
    ocupacion = 34,
    chat = 35,
    ventasPorRuta = 36,
    cargaDeMonedero = 37,
    transferencias = 38,
    depositosEnTiendasDeConveniencia = 39,
    conciliadorBancario = 40,
    conciliadorDeTransferencias = 41,
    conciliadorDeCobroEnEfectivo = 42,
    viajesEspeciales = 43,
    viajesDeTurismo = 44,
    solicitudDeRutas = 45,
    calificacionDeOperador = 46,
    calificacionDeCliente = 47,
    ventas = 48,
    analisiRutas = 49,
    operadores = 50,
    sugerencias = 51,
    pagoPorComisionCuotaYSueldoFijo = 52,
    viajesRealizados = 53,
    viajesPagados = 54,
    ocupacionPorViaje = 55,
    estadoDeCuentaPorUnidad = 56,
    estadoDeCuentaPorOperador = 57,
    contenidoGeneral = 58,
    preguntasFrecuentes = 59,
    tipovehiculo = 60,
    choferUnidad = 61,
    variablesEmpresa = 62,
    variablesGlobales = 63,
    reporteIngresosGlobal = 64,
    reporteIngresosPorEmpresa = 65,
    gestionDeClientes = 66,
    gestionDeOperadores = 67,
    gestionDeUnidades = 68,
    politicaCompensacion = 69,
    politicaCompensacionEmpresa = 70,
    ReporteOperadores = 71,
    logistica = 72,
    depositosDisponibles = 73,
    MotivoAuxilioVial = 74,
    FallaAuxilioVial = 75,
    Siniestros = 76,
    TipoDeServicios = 78,
    Zona = 79,
    Taller = 80,
    Mecanico = 91,
    TipoReparacion = 94,
    Catalogos = 90,
    Marca=95,
    Mantenimiento = 92,
    Modelo=96,
    VehiculoDetalle = 97,
    CausaSiniestro = 98,
    GrupoReparacion = 110
    }
}
